version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: job_tracker_dev_server
    depends_on:
      - db
    ports: 
      - 3000:3000
    restart: "no"
    environment: 
      - DBHOST=${DBHOST}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}

  db:
    image: postgres
    restart: "no"
    environment: 
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - development_db_data:/var/lib/postgresql/data

volumes:
  development_db_data:
