version: "3.8"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DBHOST: db
      DBUSER: postgres
      DBPASS: password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
